// packages/ag-charts-demos/src/demos/web-analytics/components/BehaviorView.tsx
import type { FunnelStep, PageRow, PathLink, Session } from '../types';
import { DurationHistogramChart } from './DurationHistogramChart';
import { EmptyState } from './EmptyState';
import { FunnelChart } from './FunnelChart';
import { PageGrid } from './PageGrid';
import { PagePerformanceChart } from './PagePerformanceChart';
import { PathFlowChart } from './PathFlowChart';

interface BehaviorViewProps {
    funnelData: FunnelStep[];
    pathData: PathLink[];
    pageData: PageRow[];
    sessions: Session[];
    hasData: boolean;
}

export function BehaviorView({ funnelData, pathData, pageData, sessions, hasData }: BehaviorViewProps) {
    return (
        <div className="wa-view">
            <section className="wa-card">
                <div className="wa-card-head">
                    <div>
                        <h2 className="wa-card-title">User paths</h2>
                    </div>
                </div>
                <div className="wa-chart-box-lg">
                    {hasData && pathData.length > 0 ? (
                        <PathFlowChart data={pathData} />
                    ) : (
                        <EmptyState message="No path data in this range" />
                    )}
                </div>
            </section>
            <div className="wa-grid-3">
                <section className="wa-card">
                    <div className="wa-card-head">
                        <div>
                            <h2 className="wa-card-title">Conversion funnel</h2>
                        </div>
                    </div>
                    <div className="wa-chart-box">
                        {hasData ? (
                            <FunnelChart data={funnelData} />
                        ) : (
                            <EmptyState message="No funnel data in this range" />
                        )}
                    </div>
                </section>
                <section className="wa-card">
                    <div className="wa-card-head">
                        <div>
                            <h2 className="wa-card-title">Session duration distribution</h2>
                        </div>
                    </div>
                    <div className="wa-chart-box">
                        {hasData ? (
                            <DurationHistogramChart sessions={sessions} />
                        ) : (
                            <EmptyState message="No session data in this range" />
                        )}
                    </div>
                </section>

                <section className="wa-card">
                    <div className="wa-card-head">
                        <div>
                            <h2 className="wa-card-title">Page views vs conversion rate</h2>
                        </div>
                    </div>
                    <div className="wa-chart-box">
                        {hasData ? (
                            <PagePerformanceChart data={pageData} />
                        ) : (
                            <EmptyState message="No page data in this range" />
                        )}
                    </div>
                </section>
            </div>

            <section className="wa-card">
                <div className="wa-card-head">
                    <div>
                        <h2 className="wa-card-title">Page performance</h2>
                    </div>
                </div>
                {hasData ? <PageGrid rows={pageData} /> : <EmptyState message="No page data in this range" />}
            </section>
        </div>
    );
}

// packages/ag-charts-demos/seeds/web-analytics/vue/src/components/BehaviorView.vue
<script setup lang="ts">
import type { FunnelStep, PageRow, PathLink, Session } from '../types';
import DurationHistogramChart from './DurationHistogramChart.vue';
import EmptyState from './EmptyState.vue';
import FunnelChart from './FunnelChart.vue';
import PagePerformanceChart from './PagePerformanceChart.vue';
import PageTreemapChart from './PageTreemapChart.vue';
import PathFlowChart from './PathFlowChart.vue';

defineProps<{
    funnelData: FunnelStep[];
    pathData: PathLink[];
    pageData: PageRow[];
    sessions: Session[];
    hasData: boolean;
}>();
</script>

<template>
    <div class="wa-view">
        <section class="wa-card">
            <div class="wa-card-head">
                <div>
                    <h2 class="wa-card-title">User paths</h2>
                </div>
            </div>
            <div class="wa-chart-box-lg">
                <PathFlowChart v-if="hasData && pathData.length > 0" :data="pathData" />
                <EmptyState v-else message="No path data in this range" />
            </div>
        </section>
        <div class="wa-grid-2-even">
            <section class="wa-card">
                <div class="wa-card-head">
                    <div>
                        <h2 class="wa-card-title">Conversion funnel</h2>
                    </div>
                </div>
                <div class="wa-chart-box">
                    <FunnelChart v-if="hasData" :data="funnelData" />
                    <EmptyState v-else message="No funnel data in this range" />
                </div>
            </section>
            <section class="wa-card">
                <div class="wa-card-head">
                    <div>
                        <h2 class="wa-card-title">Session duration distribution</h2>
                    </div>
                </div>
                <div class="wa-chart-box">
                    <DurationHistogramChart v-if="hasData" :sessions="sessions" />
                    <EmptyState v-else message="No session data in this range" />
                </div>
            </section>
        </div>
        <div class="wa-grid-2-even">
            <section class="wa-card">
                <div class="wa-card-head">
                    <div>
                        <h2 class="wa-card-title">Page views vs conversion rate</h2>
                    </div>
                </div>
                <div class="wa-chart-box">
                    <PagePerformanceChart v-if="hasData" :data="pageData" />
                    <EmptyState v-else message="No page data in this range" />
                </div>
            </section>
            <section class="wa-card">
                <div class="wa-card-head">
                    <div>
                        <h2 class="wa-card-title">Page view distribution</h2>
                    </div>
                </div>
                <div class="wa-chart-box">
                    <PageTreemapChart v-if="hasData && pageData.length > 0" :data="pageData" />
                    <EmptyState v-else message="No page data in this range" />
                </div>
            </section>
        </div>
    </div>
</template>
