// packages/ag-charts-demos/seeds/procurement/react/src/components/PurchaseOrderGrid.tsx
import type { ColDef, ICellRendererParams, ValueFormatterParams } from 'ag-grid-community';
import { AgGridReact } from 'ag-grid-react';
import { useMemo } from 'react';

import { STATUS_ICONS } from '../chartTheme';
import { fmtCurrency, fmtDate, fmtInt, fmtPrice } from '../format';
import { DATE_FILTER_PARAMS, NUMBER_FILTER_PARAMS, baseColDef, gridTheme } from '../grid';
import type { PoActionKind, PoStatus, PurchaseOrder } from '../types';

/** Grid status ink and glyph. `Delivered` is terminal, so it is chrome, not a warning. */
const STATUS_STYLE: Record<PoStatus, { className: string; icon: string }> = {
    'On time': { className: 'is-ok', icon: STATUS_ICONS['On time'] },
    'At risk': { className: 'is-warn', icon: STATUS_ICONS['At risk'] },
    Late: { className: 'is-bad', icon: STATUS_ICONS['Late'] },
    Delivered: { className: 'is-done', icon: '✓' },
};

/**
 * Status cell: glyph plus text, so the state survives without colour. The accessibility
 * requirement is that this grid and the scorecard are the accessible table equivalents of
 * the sunburst and scatter, so it has to be legible on its own terms.
 */
function StatusCell({ value }: { value: PoStatus }) {
    const style = STATUS_STYLE[value];
    return (
        <span className={`pc-status-cell ${style.className}`}>
            <span aria-hidden="true">{style.icon}</span>
            <span className="pc-status-cell-text">{value}</span>
        </span>
    );
}

const dateFormatter = ({ value }: ValueFormatterParams<PurchaseOrder, number | null>) =>
    value == null ? '—' : fmtDate(value);

/** The decisions she can record against a line, in escalating order. */
const PO_ACTIONS: { kind: PoActionKind; label: string }[] = [
    { kind: 'Resolved', label: 'Resolve' },
    { kind: 'Reassigned', label: 'Reassign' },
    { kind: 'Escalated', label: 'Escalate' },
];

interface PurchaseOrderGridProps {
    orders: PurchaseOrder[];
    /** What she has already recorded against a line, by PO id. */
    poActions: Record<string, PoActionKind>;
    onAction: (poId: string, kind: PoActionKind) => void;
}

export function PurchaseOrderGrid({ orders, poActions, onAction }: PurchaseOrderGridProps) {
    const defaultColDef = useMemo(() => baseColDef<PurchaseOrder>(), []);

    const columnDefs = useMemo<ColDef<PurchaseOrder>[]>(
        () => [
            { field: 'poId', headerName: 'PO #', minWidth: 120, filter: 'agTextColumnFilter', sort: 'desc' },
            { field: 'supplierName', headerName: 'Supplier', minWidth: 150, filter: 'agSetColumnFilter' },
            { field: 'material', headerName: 'Material', minWidth: 150, filter: 'agSetColumnFilter' },
            {
                field: 'quantity',
                headerName: 'Quantity',
                minWidth: 120,
                type: 'rightAligned',
                // Unfilterable: quantity is only comparable within one unit of measure, and the grid mixes them.
                filter: false,
                valueFormatter: ({ value, data }) => (value == null ? '' : `${fmtInt(value)} ${data?.unit ?? ''}`),
            },
            {
                field: 'unitCost',
                headerName: 'Unit cost',
                minWidth: 110,
                type: 'rightAligned',
                filter: 'agNumberColumnFilter',
                filterParams: NUMBER_FILTER_PARAMS,
                valueFormatter: ({ value }) => (value == null ? '' : fmtPrice(value)),
            },
            {
                field: 'totalCost',
                headerName: 'Cost',
                minWidth: 120,
                type: 'rightAligned',
                filter: 'agNumberColumnFilter',
                filterParams: NUMBER_FILTER_PARAMS,
                valueFormatter: ({ value }) => (value == null ? '' : fmtCurrency(value)),
            },
            {
                field: 'orderDate',
                headerName: 'Order date',
                minWidth: 130,
                filter: 'agDateColumnFilter',
                filterParams: DATE_FILTER_PARAMS,
                // The filter compares Dates, so the epoch value has to be lifted to one.
                filterValueGetter: ({ data }) => (data ? new Date(data.orderDate) : null),
                valueFormatter: dateFormatter,
            },
            {
                field: 'expectedDate',
                headerName: 'Expected delivery',
                minWidth: 150,
                filter: 'agDateColumnFilter',
                filterParams: DATE_FILTER_PARAMS,
                filterValueGetter: ({ data }) => (data ? new Date(data.expectedDate) : null),
                valueFormatter: dateFormatter,
            },
            {
                field: 'status',
                headerName: 'Status',
                minWidth: 130,
                filter: 'agSetColumnFilter',
                cellRenderer: StatusCell,
            },
            {
                colId: 'action',
                headerName: 'Action',
                minWidth: 180,
                maxWidth: 200,
                // Pinned: the other columns overflow a laptop viewport, and an action she must scroll to reach is not taken.
                pinned: 'right',
                // A control column, so nothing to sort or filter on.
                sortable: false,
                filter: false,
                resizable: false,
                cellRenderer: ({ data }: ICellRendererParams<PurchaseOrder>) => {
                    if (!data) return null;
                    const recorded = poActions[data.poId];
                    // Once a decision is recorded the line states it rather than offering the same buttons again.
                    if (recorded != null) {
                        return (
                            <span className="pc-po-action-done">
                                <span aria-hidden="true">✓</span> {recorded}
                            </span>
                        );
                    }
                    return (
                        <span className="pc-po-actions">
                            {PO_ACTIONS.map((action) => (
                                <button
                                    key={action.kind}
                                    type="button"
                                    className="pc-link-btn"
                                    onClick={() => onAction(data.poId, action.kind)}
                                >
                                    {action.label}
                                </button>
                            ))}
                        </span>
                    );
                },
            },
        ],
        [poActions, onAction]
    );

    return (
        <div className="pc-grid-host">
            <AgGridReact<PurchaseOrder>
                theme={gridTheme}
                rowData={orders}
                columnDefs={columnDefs}
                defaultColDef={defaultColDef}
                rowHeight={36}
                headerHeight={38}
                domLayout="autoHeight"
                pagination
                paginationPageSize={12}
                paginationPageSizeSelector={[12, 25, 50, 100]}
            />
        </div>
    );
}

// packages/ag-charts-demos/seeds/procurement/vue/src/components/PurchaseOrderGrid.vue
<script lang="ts">
import type { ValueFormatterParams } from 'ag-grid-community';

import { fmtDate } from '../format';
import type { PurchaseOrder } from '../types';

const dateFormatter = ({ value }: ValueFormatterParams<PurchaseOrder, number | null>) =>
    value == null ? '—' : fmtDate(value);
</script>

<script setup lang="ts">
import type { ColDef } from 'ag-grid-community';
import { AgGridVue } from 'ag-grid-vue3';
import { computed } from 'vue';

import { fmtCurrency, fmtInt, fmtPrice } from '../format';
import { DATE_FILTER_PARAMS, NUMBER_FILTER_PARAMS, baseColDef, gridTheme } from '../grid';
import type { PoActionKind } from '../types';
import PurchaseOrderActionCell from './PurchaseOrderActionCell.vue';
import StatusCell from './StatusCell.vue';

const props = defineProps<{
    orders: PurchaseOrder[];
    /** What she has already recorded against a line, by PO id. */
    poActions: Record<string, PoActionKind>;
}>();

const emit = defineEmits<{
    action: [poId: string, kind: PoActionKind];
}>();

const defaultColDef = baseColDef<PurchaseOrder>();

const onAction = (poId: string, kind: PoActionKind) => emit('action', poId, kind);

// Rebuilt when a decision is recorded, as React rebuilds it: the grid then refreshes the action
// cells with the new `cellRendererParams`.
const columnDefs = computed<ColDef<PurchaseOrder>[]>(() => [
    { field: 'poId', headerName: 'PO #', minWidth: 120, filter: 'agTextColumnFilter', sort: 'desc' },
    { field: 'supplierName', headerName: 'Supplier', minWidth: 150, filter: 'agSetColumnFilter' },
    { field: 'material', headerName: 'Material', minWidth: 150, filter: 'agSetColumnFilter' },
    {
        field: 'quantity',
        headerName: 'Quantity',
        minWidth: 120,
        type: 'rightAligned',
        // Unfilterable: quantity is only comparable within one unit of measure, and the grid mixes them.
        filter: false,
        valueFormatter: ({ value, data }) => (value == null ? '' : `${fmtInt(value)} ${data?.unit ?? ''}`),
    },
    {
        field: 'unitCost',
        headerName: 'Unit cost',
        minWidth: 110,
        type: 'rightAligned',
        filter: 'agNumberColumnFilter',
        filterParams: NUMBER_FILTER_PARAMS,
        valueFormatter: ({ value }) => (value == null ? '' : fmtPrice(value)),
    },
    {
        field: 'totalCost',
        headerName: 'Cost',
        minWidth: 120,
        type: 'rightAligned',
        filter: 'agNumberColumnFilter',
        filterParams: NUMBER_FILTER_PARAMS,
        valueFormatter: ({ value }) => (value == null ? '' : fmtCurrency(value)),
    },
    {
        field: 'orderDate',
        headerName: 'Order date',
        minWidth: 130,
        filter: 'agDateColumnFilter',
        filterParams: DATE_FILTER_PARAMS,
        // The filter compares Dates, so the epoch value has to be lifted to one.
        filterValueGetter: ({ data }) => (data ? new Date(data.orderDate) : null),
        valueFormatter: dateFormatter,
    },
    {
        field: 'expectedDate',
        headerName: 'Expected delivery',
        minWidth: 150,
        filter: 'agDateColumnFilter',
        filterParams: DATE_FILTER_PARAMS,
        filterValueGetter: ({ data }) => (data ? new Date(data.expectedDate) : null),
        valueFormatter: dateFormatter,
    },
    {
        field: 'status',
        headerName: 'Status',
        minWidth: 130,
        filter: 'agSetColumnFilter',
        cellRenderer: StatusCell,
    },
    {
        colId: 'action',
        headerName: 'Action',
        minWidth: 180,
        maxWidth: 200,
        // Pinned: the other columns overflow a laptop viewport, and an action she must scroll to reach is not taken.
        pinned: 'right',
        // A control column, so nothing to sort or filter on.
        sortable: false,
        filter: false,
        resizable: false,
        cellRenderer: PurchaseOrderActionCell,
        cellRendererParams: { poActions: props.poActions, onAction },
    },
]);
</script>

<template>
    <div class="pc-grid-host">
        <AgGridVue
            :theme="gridTheme"
            :row-data="orders"
            :column-defs="columnDefs"
            :default-col-def="defaultColDef"
            :row-height="36"
            :header-height="38"
            dom-layout="autoHeight"
            :pagination="true"
            :pagination-page-size="12"
            :pagination-page-size-selector="[12, 25, 50, 100]"
        />
    </div>
</template>
