// packages/ag-charts-demos/seeds/procurement/angular/src/components/shipment-schedule.ts
import { Component, computed, input, output } from '@angular/core';

import { AgCharts } from 'ag-charts-angular';
import type { AgCartesianChartOptions, AgRangeBarSeriesOptions, AgScatterSeriesOptions } from 'ag-charts-community';

import { NEUTRAL, STATUS_COLORS, THEME } from '../chartTheme';
import { DEMO_NOW } from '../data';
import { fmtCurrencyCompact, fmtDate, fmtSlack } from '../format';
import type { TrackedShipment } from '../types';
import { AfterRender } from '../ui';

/** One row of the schedule: a shipment's transit window plus the date it is needed. */
interface Leg {
    shipmentId: string;
    supplier: string;
    material: string;
    plant: string;
    depart: number;
    projected: number;
    required: number;
    status: TrackedShipment['status'];
    slackDays: number;
    value: number;
}

/**
 * Fixed bar thickness. This is what makes the chart scrollable: a fixed width means the rows
 * need whatever height they need, and the scrollbar pans the overflow rather than the axis
 * squeezing every bar to a hairline.
 */
const BAR_WIDTH = 16;

/**
 * Every shipment's transit window against the date production needs it.
 *
 * The at-risk rule *is* the gap between the projected arrival and the required date, so this
 * draws the decision criterion as a length rather than restating it as "3d buffer" text. A bar
 * whose end passes its required marker is late, and by how much is directly readable — which the
 * status board's tiles can only tell her one shipment at a time.
 *
 * The host is the chart's container, the `<div>` the React `AgCharts` wrapper renders.
 */
@Component({
    selector: 'div[pcShipmentSchedule]',
    imports: [AfterRender, AgCharts],
    host: { style: 'height: 100%; width: 100%;' },
    template: '<ag-charts *pcAfterRender style="display: block; height: 100%; width: 100%;" [options]="options()" />',
})
export class ShipmentSchedule {
    readonly shipments = input.required<TrackedShipment[]>();
    /** The shipment currently selected, if any. */
    readonly selectedShipmentId = input<string | undefined>();
    /** Selecting the same shipment again clears it. */
    readonly select = output<string>();

    // Soonest required first, so what is most urgent is at the top of the axis.
    private readonly legs = computed<Leg[]>(() =>
        [...this.shipments()]
            .sort((a, b) => a.requiredDate - b.requiredDate)
            .map((shipment) => ({
                shipmentId: shipment.shipmentId,
                supplier: shipment.supplierName,
                material: shipment.material,
                plant: shipment.plantName,
                depart: shipment.departDate,
                projected: shipment.projectedDate,
                required: shipment.requiredDate,
                status: shipment.status,
                slackDays: shipment.slackDays,
                value: shipment.value,
            }))
    );

    protected readonly options = computed<AgCartesianChartOptions<Leg>>(() => {
        const selectedShipmentId = this.selectedShipmentId();
        const dimmed = (shipmentId: string) => selectedShipmentId != null && shipmentId !== selectedShipmentId;

        const transit: AgRangeBarSeriesOptions<Leg> = {
            type: 'range-bar',
            direction: 'horizontal',
            xKey: 'shipmentId',
            yLowKey: 'depart',
            yHighKey: 'projected',
            yName: 'In transit',
            width: BAR_WIDTH,
            cornerRadius: 3,
            strokeWidth: 0,
            itemStyler: ({ datum }) =>
                dimmed(datum.shipmentId)
                    ? { fill: NEUTRAL, fillOpacity: 0.3 }
                    : { fill: STATUS_COLORS[datum.status], fillOpacity: 0.9 },
            tooltip: {
                renderer: ({ datum }) => ({
                    title: `${datum.shipmentId} · ${datum.status}`,
                    data: [
                        { label: 'Lane', value: `${datum.supplier} → ${datum.plant}` },
                        { label: 'Cargo', value: datum.material },
                        { label: 'Despatched', value: fmtDate(datum.depart) },
                        { label: 'Projected arrival', value: fmtDate(datum.projected) },
                        { label: 'Required by', value: fmtDate(datum.required) },
                        { label: 'Against required', value: fmtSlack(datum.slackDays) },
                        { label: 'Value', value: fmtCurrencyCompact(datum.value) },
                    ],
                }),
            },
            listeners: {
                seriesNodeClick: ({ datum }) => this.select.emit(datum.shipmentId),
            },
        };

        // The date production needs it, as a separate mark so it reads against the bar's end
        // rather than as part of it.
        const required: AgScatterSeriesOptions<Leg> = {
            type: 'scatter',
            xKey: 'required',
            yKey: 'shipmentId',
            yName: 'Required by',
            shape: 'diamond',
            size: 11,
            fill: 'var(--pc-text)',
            stroke: 'var(--pc-text)',
            strokeWidth: 2,
            tooltip: { enabled: false },
            highlight: { enabled: false },
            listeners: {
                seriesNodeClick: ({ datum }) => this.select.emit(datum.shipmentId),
            },
        };

        return {
            theme: THEME,
            data: this.legs(),
            series: [transit, required],
            // Horizontal bars: shipments down the left, time along the bottom.
            axes: {
                y: { type: 'category', position: 'left', label: { fontSize: 11 } },
                x: {
                    type: 'time',
                    position: 'bottom',
                    crossLines: [
                        {
                            type: 'line',
                            value: DEMO_NOW,
                            stroke: 'var(--pc-text)',
                            strokeWidth: 1.5,
                            label: {
                                enabled: true,
                                text: 'Today',
                                placement: 'top',
                                color: 'var(--pc-text)',
                                fontSize: 11,
                            },
                        },
                    ],
                },
            },
            legend: { enabled: false },
            // The rows overflow a short card, so panning is by scrollbar rather than by the
            // card growing to fit however many shipments are in transit.
            scrollbar: { enabled: true, vertical: { position: 'right' } },
            padding: { top: 8, right: 16, bottom: 4, left: 4 },
        };
    });
}

// packages/ag-charts-demos/seeds/procurement/vue/src/components/ShipmentSchedule.vue
<script lang="ts">
import type { TrackedShipment } from '../types';

/** One row of the schedule: a shipment's transit window plus the date it is needed. */
interface Leg {
    shipmentId: string;
    supplier: string;
    material: string;
    plant: string;
    depart: number;
    projected: number;
    required: number;
    status: TrackedShipment['status'];
    slackDays: number;
    value: number;
}

/**
 * Fixed bar thickness. This is what makes the chart scrollable: a fixed width means the rows
 * need whatever height they need, and the scrollbar pans the overflow rather than the axis
 * squeezing every bar to a hairline.
 */
const BAR_WIDTH = 16;
</script>

<script setup lang="ts">
import { computed } from 'vue';

import type { AgCartesianChartOptions, AgRangeBarSeriesOptions, AgScatterSeriesOptions } from 'ag-charts-community';
import { AgCharts } from 'ag-charts-vue3';

import { NEUTRAL, STATUS_COLORS, THEME } from '../chartTheme';
import { DEMO_NOW } from '../data';
import { fmtCurrencyCompact, fmtDate, fmtSlack } from '../format';

/**
 * Every shipment's transit window against the date production needs it.
 *
 * The at-risk rule *is* the gap between the projected arrival and the required date, so this
 * draws the decision criterion as a length rather than restating it as "3d buffer" text. A bar
 * whose end passes its required marker is late, and by how much is directly readable — which the
 * status board's tiles can only tell her one shipment at a time.
 */
const props = defineProps<{
    shipments: TrackedShipment[];
    /** The shipment currently selected, if any. */
    selectedShipmentId?: string;
}>();

const emit = defineEmits<{
    /** Selecting the same shipment again clears it. */
    select: [shipmentId: string];
}>();

// Soonest required first, so what is most urgent is at the top of the axis.
const legs = computed<Leg[]>(() =>
    [...props.shipments]
        .sort((a, b) => a.requiredDate - b.requiredDate)
        .map((shipment) => ({
            shipmentId: shipment.shipmentId,
            supplier: shipment.supplierName,
            material: shipment.material,
            plant: shipment.plantName,
            depart: shipment.departDate,
            projected: shipment.projectedDate,
            required: shipment.requiredDate,
            status: shipment.status,
            slackDays: shipment.slackDays,
            value: shipment.value,
        }))
);

const options = computed<AgCartesianChartOptions<Leg>>(() => {
    const { selectedShipmentId } = props;
    const dimmed = (shipmentId: string) => selectedShipmentId != null && shipmentId !== selectedShipmentId;

    const transit: AgRangeBarSeriesOptions<Leg> = {
        type: 'range-bar',
        direction: 'horizontal',
        xKey: 'shipmentId',
        yLowKey: 'depart',
        yHighKey: 'projected',
        yName: 'In transit',
        width: BAR_WIDTH,
        cornerRadius: 3,
        strokeWidth: 0,
        itemStyler: ({ datum }) =>
            dimmed(datum.shipmentId)
                ? { fill: NEUTRAL, fillOpacity: 0.3 }
                : { fill: STATUS_COLORS[datum.status], fillOpacity: 0.9 },
        tooltip: {
            renderer: ({ datum }) => ({
                title: `${datum.shipmentId} · ${datum.status}`,
                data: [
                    { label: 'Lane', value: `${datum.supplier} → ${datum.plant}` },
                    { label: 'Cargo', value: datum.material },
                    { label: 'Despatched', value: fmtDate(datum.depart) },
                    { label: 'Projected arrival', value: fmtDate(datum.projected) },
                    { label: 'Required by', value: fmtDate(datum.required) },
                    { label: 'Against required', value: fmtSlack(datum.slackDays) },
                    { label: 'Value', value: fmtCurrencyCompact(datum.value) },
                ],
            }),
        },
        listeners: {
            seriesNodeClick: ({ datum }) => emit('select', datum.shipmentId),
        },
    };

    // The date production needs it, as a separate mark so it reads against the bar's end
    // rather than as part of it.
    const required: AgScatterSeriesOptions<Leg> = {
        type: 'scatter',
        xKey: 'required',
        yKey: 'shipmentId',
        yName: 'Required by',
        shape: 'diamond',
        size: 11,
        fill: 'var(--pc-text)',
        stroke: 'var(--pc-text)',
        strokeWidth: 2,
        tooltip: { enabled: false },
        highlight: { enabled: false },
        listeners: {
            seriesNodeClick: ({ datum }) => emit('select', datum.shipmentId),
        },
    };

    return {
        theme: THEME,
        data: legs.value,
        series: [transit, required],
        // Horizontal bars: shipments down the left, time along the bottom.
        axes: {
            y: { type: 'category', position: 'left', label: { fontSize: 11 } },
            x: {
                type: 'time',
                position: 'bottom',
                crossLines: [
                    {
                        type: 'line',
                        value: DEMO_NOW,
                        stroke: 'var(--pc-text)',
                        strokeWidth: 1.5,
                        label: {
                            enabled: true,
                            text: 'Today',
                            placement: 'top',
                            color: 'var(--pc-text)',
                            fontSize: 11,
                        },
                    },
                ],
            },
        },
        legend: { enabled: false },
        // The rows overflow a short card, so panning is by scrollbar rather than by the
        // card growing to fit however many shipments are in transit.
        scrollbar: { enabled: true, vertical: { position: 'right' } },
        padding: { top: 8, right: 16, bottom: 4, left: 4 },
    };
});
</script>

<template>
    <AgCharts :options="options" :style="{ height: '100%', width: '100%' }" />
</template>
