// packages/ag-charts-demos/seeds/web-analytics/vue/src/components/OverviewView.vue
<script setup lang="ts">
import { PopoverAnchor, PopoverContent, PopoverPortal, PopoverRoot, PopoverTrigger } from 'reka-ui';
import { computed, ref, shallowRef, watch } from 'vue';

import type { DailyPoint } from '../data';
import { fmtInt } from '../format';
import type { MetricKey } from '../metrics';
import type { Annotation, AnnotationType, Session } from '../types';
import EmptyState from './EmptyState.vue';
import EventForm, { type FormAnchor } from './EventForm.vue';
import KpiTiles, { type KpiDef, kpiTabId } from './KpiTiles.vue';
import SessionsGrid from './SessionsGrid.vue';
import TrafficChart from './TrafficChart.vue';
import { dayKey, sameDaySet } from './dateFilter';

const props = defineProps<{
    daily: DailyPoint[];
    dailyPrevious: DailyPoint[];
    /** Every session in the selected range — feeds the sessions grid. */
    sessions: Session[];
    annotations: Annotation[];
    kpis: KpiDef[];
    /** The metric currently driving the traffic chart. */
    metric: MetricKey;
    hasData: boolean;
}>();
const emit = defineEmits<{
    metricSelect: [key: MetricKey];
    annotationAdd: [date: Date, label: string, type: AnnotationType];
    annotationRemove: [annotationId: string];
}>();

// Days selected on the traffic chart narrow the sessions grid; empty = whole range.
const selectedDays = shallowRef<Date[]>([]);
// Reported back by the grid; feeds the card's count and never reaches the chart.
const filterModel = shallowRef<Record<string, unknown>>({});
const displayedRowCount = ref(0);
const onGridStateChange = (model: Record<string, unknown>, rowCount: number) => {
    filterModel.value = model;
    displayedRowCount.value = rowCount;
};
const gridRef = ref<InstanceType<typeof SessionsGrid>>();
// Clicked annotation, and the day the add-event form is open on (null = closed).
const selectedAnnotationId = ref<string | null>(null);
const formDay = shallowRef<Date | null>(null);
// Where the form opens: the right-clicked point, or under the toolbar button.
const formAnchor = shallowRef<FormAnchor | undefined>();

const selectedAnnotation = computed(() => props.annotations.find((a) => a.annotationId === selectedAnnotationId.value));

// Dropping out of the date range deselects for good, so widening it again does not resurrect it.
watch(
    [selectedAnnotationId, selectedAnnotation],
    ([annotationId, annotation]) => {
        if (annotationId != null && !annotation) selectedAnnotationId.value = null;
    },
    { flush: 'post' }
);
// The charted day domain, which also bounds the form's date field.
const firstDay = computed(() => props.daily[0]?.date);
const lastDay = computed(() => props.daily.at(-1)?.date);

// Clicking the selected annotation again deselects it.
const selectAnnotation = (annotationId: string | null) => {
    const prev = selectedAnnotationId.value;
    selectedAnnotationId.value = annotationId != null && annotationId === prev ? null : annotationId;
};

const removeAnnotation = (annotationId: string) => {
    if (selectedAnnotationId.value === annotationId) selectedAnnotationId.value = null;
    emit('annotationRemove', annotationId);
};

const openEventForm = (day: Date, anchor?: FormAnchor) => {
    formDay.value = day;
    formAnchor.value = anchor;
};

// A right-click opens the form at the pointer; the toolbar button anchors it itself.
const pointAnchor = computed(() => {
    const anchor = formAnchor.value;
    return anchor && { getBoundingClientRect: () => new DOMRect(anchor.x, anchor.y, 0, 0) };
});

// The popover reports its open state; opening from the trigger lands on the last charted day.
const onOpenChange = (open: boolean) => {
    if (open && lastDay.value) openEventForm(lastDay.value);
    else formDay.value = null;
};

const addEvent = (date: Date, label: string, type: AnnotationType) => {
    formDay.value = null;
    emit('annotationAdd', date, label, type);
};

const activeFilterCount = computed(() => Object.keys(filterModel.value).length);

// Only the column filters; the chart selection is cleared by clicking empty chart space.
const clearFilters = () => gridRef.value?.clearFilters();

// Ignore no-op updates so re-selecting the same days does not churn the grid's row data.
const setDays = (days: Date[]) => {
    if (!sameDaySet(selectedDays.value, days)) selectedDays.value = days;
};

// The grid's row data, which its column filters then narrow.
const daySessions = computed(() => {
    if (selectedDays.value.length === 0) return [];
    const keys = new Set(selectedDays.value.map(dayKey));
    return props.sessions.filter((s) => keys.has(dayKey(new Date(s.timestamp))));
});

const gridSummary = computed(() => {
    const count = selectedDays.value.length;
    if (count === 0) {
        return `No days selected.`;
    }
    const days = `${count} selected ${count === 1 ? 'day' : 'days'}`;
    const filters = activeFilterCount.value;
    if (filters === 0) return `${fmtInt(daySessions.value.length)} sessions on ${days}`;
    return (
        `${fmtInt(displayedRowCount.value)} out of ${fmtInt(daySessions.value.length)} sessions on ${days} ` +
        `(${filters} ${filters === 1 ? 'filter' : 'filters'} applied)`
    );
});
</script>

<template>
    <div class="wa-view">
        <section class="wa-card wa-card--tabbed">
            <KpiTiles :kpis="kpis" :active-key="metric" @select="emit('metricSelect', $event)" />
            <div class="wa-card-head">
                <div>
                    <h2 class="wa-card-title">Traffic over time</h2>
                </div>
                <div class="wa-card-actions">
                    <button
                        v-if="selectedAnnotation"
                        class="wa-btn"
                        v-text="`Remove “${selectedAnnotation.label}”`"
                        @click="removeAnnotation(selectedAnnotation.annotationId)"
                    />
                    <PopoverRoot :open="formDay != null" @update:open="onOpenChange">
                        <!-- Renders no element of its own (as-child with no child), like Radix's
                             virtual-ref Anchor; it only moves the popover's reference point. -->
                        <PopoverAnchor v-if="pointAnchor" as-child :reference="pointAnchor" />
                        <PopoverTrigger class="wa-btn wa-btn--secondary" :disabled="!lastDay">Add event</PopoverTrigger>
                        <PopoverPortal>
                            <PopoverContent
                                class="wa-portal"
                                side="bottom"
                                align="end"
                                :side-offset="6"
                                :collision-padding="8"
                            >
                                <EventForm
                                    v-if="formDay != null && firstDay && lastDay"
                                    :key="formDay.getTime()"
                                    :date="formDay"
                                    :min-date="firstDay"
                                    :max-date="lastDay"
                                    @submit="addEvent"
                                    @cancel="formDay = null"
                                />
                                <!-- Reopening on another day starts the form afresh (the key). -->
                            </PopoverContent>
                        </PopoverPortal>
                    </PopoverRoot>
                </div>
            </div>
            <div class="wa-chart-box-lg" role="tabpanel" :aria-labelledby="kpiTabId(metric)">
                <TrafficChart
                    v-if="hasData"
                    :metric="metric"
                    :daily="daily"
                    :daily-previous="dailyPrevious"
                    :annotations="annotations"
                    :selected-days="selectedDays"
                    :selected-annotation-id="selectedAnnotation?.annotationId ?? null"
                    @selection-change="setDays"
                    @annotation-select="selectAnnotation"
                    @annotation-remove="removeAnnotation"
                    @add-event-at="openEventForm"
                />
                <EmptyState v-else message="No sessions in this date range" hint="Try widening the range." />
            </div>
        </section>

        <section class="wa-card">
            <div class="wa-card-head">
                <div>
                    <h2 class="wa-card-title">Sessions</h2>
                    <span class="wa-card-sub">{{ gridSummary }}</span>
                </div>
                <button class="wa-btn" :disabled="activeFilterCount === 0" @click="clearFilters">Clear filters</button>
            </div>
            <SessionsGrid v-if="hasData" ref="gridRef" :sessions="daySessions" @grid-state-change="onGridStateChange" />
            <EmptyState v-else message="No sessions in this date range" hint="Try widening the range." />
        </section>
    </div>
</template>

// packages/ag-charts-demos/seeds/web-analytics/react/src/components/OverviewView.tsx
import * as RPopover from '@radix-ui/react-popover';
import { useCallback, useEffect, useMemo, useRef, useState } from 'react';

import type { DailyPoint } from '../data';
import { fmtInt } from '../format';
import type { MetricKey } from '../metrics';
import type { Annotation, AnnotationType, Session } from '../types';
import { EmptyState } from './EmptyState';
import { EventForm, type FormAnchor } from './EventForm';
import { type KpiDef, KpiTiles, kpiTabId } from './KpiTiles';
import { SessionsGrid, type SessionsGridHandle } from './SessionsGrid';
import { TrafficChart } from './TrafficChart';
import { dayKey, sameDaySet } from './dateFilter';

interface OverviewViewProps {
    daily: DailyPoint[];
    dailyPrevious: DailyPoint[];
    /** Every session in the selected range — feeds the sessions grid. */
    sessions: Session[];
    annotations: Annotation[];
    kpis: KpiDef[];
    /** The metric currently driving the traffic chart. */
    metric: MetricKey;
    hasData: boolean;
    onMetricSelect: (key: MetricKey) => void;
    onAnnotationAdd: (date: Date, label: string, type: AnnotationType) => void;
    onAnnotationRemove: (annotationId: string) => void;
}

export function OverviewView({
    daily,
    dailyPrevious,
    sessions,
    annotations,
    kpis,
    metric,
    hasData,
    onMetricSelect,
    onAnnotationAdd,
    onAnnotationRemove,
}: OverviewViewProps) {
    // Days selected on the traffic chart narrow the sessions grid; empty = whole range.
    const [selectedDays, setSelectedDays] = useState<Date[]>([]);
    // Reported back by the grid; feeds the card's count and never reaches the chart.
    const [filterModel, setFilterModel] = useState<Record<string, unknown>>({});
    const [displayedRowCount, setDisplayedRowCount] = useState(0);
    const onGridStateChange = useCallback((model: Record<string, unknown>, rowCount: number) => {
        setFilterModel(model);
        setDisplayedRowCount(rowCount);
    }, []);
    const gridRef = useRef<SessionsGridHandle>(null);
    // Clicked annotation, and the day the add-event form is open on (null = closed).
    const [selectedAnnotationId, setSelectedAnnotationId] = useState<string | null>(null);
    const [formDay, setFormDay] = useState<Date | null>(null);
    // Where the form opens: the right-clicked point, or under the toolbar button.
    const [formAnchor, setFormAnchor] = useState<FormAnchor | undefined>();

    const selectedAnnotation = annotations.find((a) => a.annotationId === selectedAnnotationId);

    // Dropping out of the date range deselects for good, so widening it again does not resurrect it.
    useEffect(() => {
        if (selectedAnnotationId != null && !selectedAnnotation) setSelectedAnnotationId(null);
    }, [selectedAnnotationId, selectedAnnotation]);
    // The charted day domain, which also bounds the form's date field.
    const firstDay = daily[0]?.date;
    const lastDay = daily.at(-1)?.date;

    // Clicking the selected annotation again deselects it.
    const selectAnnotation = useCallback(
        (annotationId: string | null) =>
            setSelectedAnnotationId((prev) => (annotationId != null && annotationId === prev ? null : annotationId)),
        []
    );

    const removeAnnotation = useCallback(
        (annotationId: string) => {
            setSelectedAnnotationId((prev) => (prev === annotationId ? null : prev));
            onAnnotationRemove(annotationId);
        },
        [onAnnotationRemove]
    );

    const openEventForm = useCallback((day: Date, anchor?: FormAnchor) => {
        setFormDay(day);
        setFormAnchor(anchor);
    }, []);

    // A right-click opens the form at the pointer; the toolbar button anchors it itself.
    const pointAnchor = useMemo(
        () =>
            formAnchor && {
                current: { getBoundingClientRect: () => new DOMRect(formAnchor.x, formAnchor.y, 0, 0) },
            },
        [formAnchor]
    );

    const addEvent = useCallback(
        (date: Date, label: string, type: AnnotationType) => {
            setFormDay(null);
            onAnnotationAdd(date, label, type);
        },
        [onAnnotationAdd]
    );

    const activeFilterCount = useMemo(() => Object.keys(filterModel).length, [filterModel]);

    // Only the column filters; the chart selection is cleared by clicking empty chart space.
    const clearFilters = useCallback(() => gridRef.current?.clearFilters(), []);

    // Ignore no-op updates so re-selecting the same days does not churn the grid's row data.
    const setDays = useCallback(
        (days: Date[]) => setSelectedDays((prev) => (sameDaySet(prev, days) ? prev : days)),
        []
    );

    // The grid's row data, which its column filters then narrow.
    const daySessions = useMemo(() => {
        if (selectedDays.length === 0) return [];
        const keys = new Set(selectedDays.map(dayKey));
        return sessions.filter((s) => keys.has(dayKey(new Date(s.timestamp))));
    }, [sessions, selectedDays]);

    const gridSummary = useMemo(() => {
        if (selectedDays.length === 0) {
            return `No days selected.`;
        }
        const days = `${selectedDays.length} selected ${selectedDays.length === 1 ? 'day' : 'days'}`;
        if (activeFilterCount === 0) return `${fmtInt(daySessions.length)} sessions on ${days}`;
        return (
            `${fmtInt(displayedRowCount)} out of ${fmtInt(daySessions.length)} sessions on ${days} ` +
            `(${activeFilterCount} ${activeFilterCount === 1 ? 'filter' : 'filters'} applied)`
        );
    }, [selectedDays, activeFilterCount, daySessions, displayedRowCount]);

    return (
        <div className="wa-view">
            <section className="wa-card wa-card--tabbed">
                <KpiTiles kpis={kpis} activeKey={metric} onSelect={onMetricSelect} />
                <div className="wa-card-head">
                    <div>
                        <h2 className="wa-card-title">Traffic over time</h2>
                    </div>
                    <div className="wa-card-actions">
                        {selectedAnnotation && (
                            <button
                                className="wa-btn"
                                onClick={() => removeAnnotation(selectedAnnotation.annotationId)}
                            >
                                Remove &ldquo;{selectedAnnotation.label}&rdquo;
                            </button>
                        )}
                        <RPopover.Root
                            open={formDay != null}
                            onOpenChange={(open) => (open && lastDay ? openEventForm(lastDay) : setFormDay(null))}
                        >
                            {pointAnchor && <RPopover.Anchor virtualRef={pointAnchor} />}
                            <RPopover.Trigger className="wa-btn wa-btn--secondary" disabled={!lastDay}>
                                Add event
                            </RPopover.Trigger>
                            <RPopover.Portal>
                                <RPopover.Content
                                    className="wa-portal"
                                    side="bottom"
                                    align="end"
                                    sideOffset={6}
                                    collisionPadding={8}
                                >
                                    {formDay != null && firstDay && lastDay && (
                                        <EventForm
                                            // Reopening on another day starts the form afresh.
                                            key={formDay.getTime()}
                                            date={formDay}
                                            minDate={firstDay}
                                            maxDate={lastDay}
                                            onSubmit={addEvent}
                                            onCancel={() => setFormDay(null)}
                                        />
                                    )}
                                </RPopover.Content>
                            </RPopover.Portal>
                        </RPopover.Root>
                    </div>
                </div>
                <div className="wa-chart-box-lg" role="tabpanel" aria-labelledby={kpiTabId(metric)}>
                    {hasData ? (
                        <TrafficChart
                            metric={metric}
                            daily={daily}
                            dailyPrevious={dailyPrevious}
                            annotations={annotations}
                            selectedDays={selectedDays}
                            onSelectionChange={setDays}
                            selectedAnnotationId={selectedAnnotation?.annotationId ?? null}
                            onAnnotationSelect={selectAnnotation}
                            onAnnotationRemove={removeAnnotation}
                            onAddEventAt={openEventForm}
                        />
                    ) : (
                        <EmptyState message="No sessions in this date range" hint="Try widening the range." />
                    )}
                </div>
            </section>

            <section className="wa-card">
                <div className="wa-card-head">
                    <div>
                        <h2 className="wa-card-title">Sessions</h2>
                        <span className="wa-card-sub">{gridSummary}</span>
                    </div>
                    <button className="wa-btn" onClick={clearFilters} disabled={activeFilterCount === 0}>
                        Clear filters
                    </button>
                </div>
                {hasData ? (
                    <SessionsGrid ref={gridRef} sessions={daySessions} onGridStateChange={onGridStateChange} />
                ) : (
                    <EmptyState message="No sessions in this date range" hint="Try widening the range." />
                )}
            </section>
        </div>
    );
}
